version: "3.8"

services:
  server:
    container_name: hanaverse-api
    build:
      context: ./packages/@hanaverse-api
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 3000
    ports:
      - 127.0.0.1:7080:3000
    depends_on:
      - database

  database:
    container_name: hanaverse-database
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: hanaverse
      POSTGRES_PASSWORD: hanaverse
      POSTGRES_DB: hanaverse-db
    ports:
      - 127.0.0.1:7090:5432
    volumes:
      - "db:/var/lib/postgresql/data"

  client:
    container_name: hanaverse-client
    build:
      context: ./packages/hanaverse-client
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - 127.0.0.1:8080:8080

volumes:
  db:
    driver: local
