spring:
  application:
    name: hanaverse-api
  datasource:
    url: jdbc:postgresql://wapcwtycyayjfc:a32710045c698c0008a5b6d6907c0504d0a3bb9ae86df279b89d7441d819dbb2@ec2-35-168-80-116.compute-1.amazonaws.com:5432/d6hbfl7hk6f5te
    username: hanaverse
    password: hanaverse
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true
  liquibase.change-log:
    classpath:liquibase/master.xml

server:
  port: 3000
