spring:
  application:
    name: hanaverse-api
  datasource:
    url: jdbc:postgresql://localhost:7090/hanaverse-db
    username: hanaverse
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: hanaverse:europe-north1:hanaverse
  jpa:
    show-sql: true
  liquibase.change-log:
    classpath:liquibase/master.xml

server:
  port: ${PORT:3000}
